[profile.default]
libs = ["lib"]
out = "out"
src = "src"

[etherscan]
mainnet = {key = "${ETHERSCAN_API_KEY}"}
sepolia = {key = "${ETHERSCAN_API_KEY}"}

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_ENDPOINT}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
